Django - User Authentication and Sessions/library/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('create_book/',views.BookCreateView.as_view(),name='create_view'),
    path('book/<int:pk>/',views.BookDetailView.as_view(),name='book_detail'),
    path('my_view/',views.my_views, name='my_view'),
    path('signup/',views.SignUpView.as_view(),name='signup'),
    path('profile/',views.CheckedOutBooksByUserView.as_view(),name="profile")
]

Django - User Authentication and Sessions/library/library/urls.py
from django.contrib import admin
from django.urls import path,include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('',RedirectView.as_view(url='catalog/')),
    path('accounts/',include('django.contrib.auth.urls'))
]

Django - User Authentication and Sessions/library/catalog/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.

class Genre(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author',on_delete=models.SET_NULL,null=True)
    summary = models.TextField(max_length=600)
    isbn = models.CharField("ISBN",max_length=13,unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey('Language',on_delete=models.SET_NULL,null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})
    

class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    birth_of_date = models.DateField(null=True,blank=True)

    class Meta:
        ordering = ['first_name','last_name']

    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})

    def __str__(self):
        return f"{self.last_name} , {self.first_name}"

import uuid

class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4)
    book = models.ForeignKey('Book',on_delete=models.RESTRICT,null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True,blank=True)
    borrowed = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)

    LOAN_STATUS = (
        ('m', 'Maintance'),
        ('o', 'On Loan'),
        ('a', 'Available'),
        ('r', 'Reserved')
    )

    status = models.CharField(max_length=1,choices=LOAN_STATUS,blank=True,default='m')

    class Meta:
        ordering = ['due_back']

    def __str__(self):
        return f"{self.id} ({self.book.title})"

class Language(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

Django - User Authentication and Sessions/library/catalog/views.py
from django.shortcuts import render
from .models import BookInstance, Book
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
# Create your views here.

def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()
    num_instances_avail = BookInstance.objects.filter(status__exact="a").count()

    context = {
        'num_books':num_books,
        'num_instances':num_instances,
        'num_instances_avail':num_instances_avail
    }
    return render(request,'catalog/index.html',context=context)


class BookCreateView(LoginRequiredMixin,CreateView):
    model = Book
    fields = "__all__"

class BookDetailView(DetailView):
    model = Book

@login_required
def my_views(request):
    return render(request,'catalog/my_view.html')

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'catalog/signup.html'

class CheckedOutBooksByUserView(LoginRequiredMixin,ListView):
    model = BookInstance
    template_name = 'catalog/profile.html'
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrowed=self.request.user) 
    

Django - User Authentication and Sessions/library/catalog/templates/catalog/book_detail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Detail for book</h1>
   {{book}} 
</body>
</html>

Django - User Authentication and Sessions/library/catalog/templates/catalog/book_form.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>CREATE NEW BOOK</h2>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Create">
    </form>
</body>
</html>

Django - User Authentication and Sessions/library/catalog/templates/catalog/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOMEPAGE</h1>
    <p>Total Books: {{num_books}}</p>
    <p>Num Available: {{num_instances_avail}}</p>
    {% if user.is_authenticated%}
        <p>You are Logged In</p>
        <p>Welcome: {{user.get_username}}</p>
        <a href="{% url 'logout' %}?next={{request.path}}">LOGOUT</a>
    {% else %}
    <p>You are not Logged In</p>
    <a href="{% url 'login' %}?next={{request.path}}">LOGIN</a>
    {% endif %}
</body>
</html>

Django - User Authentication and Sessions/library/catalog/templates/catalog/my_view.html
<h1>LOGGED IN USERS ONLY!!!</h1>

Django - User Authentication and Sessions/library/catalog/templates/catalog/profile.html
<h1>Welcome to your profile</h1>
<p>Your Books:</p>
{% for book in bookinstance_list %}
    <p>{{book}}</p>
{% endfor %}    

Django - User Authentication and Sessions/library/catalog/templates/catalog/signup.html
<h1>Register Name User</h1>
<form method="post">
    {%csrf_token%}
    {{form.as_p}}
    <input type="submit" value="Sign up">
</form>