Django Admin/my_car_site/cars/urls.py
from django.urls import path
from . import views

app_name = "cars"

urlpatterns = [
    path('add/',views.add,name="add"),
    path('delete/',views.delete,name="delete"),
    path('list/',views.list,name="list"),
]

Django Admin/my_car_site/my_car_site/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls')),
]

Django Admin/my_car_site/cars/models.py
from django.db import models

# Create your models here.

class Cars(models.Model):
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self) -> str:
        return f"{self.brand} {self.year}"

    

Django Admin/my_car_site/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.

def add(request):
    if request.POST:
        brand = request.POST["brand"]
        year = request.POST["year"]
        models.Cars.objects.create(brand=brand,year=year)
        return redirect(reverse("cars:list"))
    else:
        return render(request,"cars/add.html")

def delete(request):
    if request.POST:
        pk = request.POST["pk"]
        try:
            models.Cars.objects.get(pk=pk).delete()
            return redirect(reverse("cars:list"))
        except:
            print(f"PK:{pk} not founded")
            return redirect(reverse("cars:list"))
    else:        
        return render(request,"cars/delete.html")

def list(request):
    all_cars = models.Cars.objects.all()
    context_cars = {"all_cars":all_cars}
    return render(request,"cars/list.html",context=context_cars)

Django Admin/my_car_site/cars/templates/cars/add.html
{% extends 'base.html' %}
{% block content %}

<div class='container'>
    <h1>ADD.HTML</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="brand">Brand:</label>
            <input class="form-control" type="text" name="brand" id="brand"> 
        </div> 
        <div clas="form-group">
            <label for="year">Year:</label>
            <input class="form-control" type="text" name="year" id="year"> 
        </div>
        <input class="btn btn-primary" type="submit">
    </form>
</div>
{% endblock  %}

Django Admin/my_car_site/cars/templates/cars/delete.html
{% extends 'base.html' %}
{% block content %}
<h1>DELETE.HTML</h1>
<div class="container">
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="pk">PK Number:</label>
            <input class="form-control" type="text" id="pk" name="pk">
        </div>
        <input type="submit" class="btn btn-primary">
    </form>
</div>
{% endblock  %}

Django Admin/my_car_site/cars/templates/cars/list.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>
    <h1>LIST.HTML</h1>
    <ul>
        {% for car in all_cars %}
            <li>{{car}}</li>
        {% endfor %}
    </ul>    
</div>
{% endblock  %}

Django Admin/my_car_site/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
              <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
              <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
            </div>
          </div>
        </div>
      </nav>
    {% block content %}
    {% endblock  %}
</body>
</html>