Django Class Based Views/school/classroom/urls.py
from django.urls import path
from .views import (HomeView,ThankYouView,
                    ContactFormView,TeacherCreateView,
                    TeacherListView,TeacherDetailView,
                    TeacherUpdateView,TeacherDeleteView)

app_name = 'classroom'

urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('thank_you/',ThankYouView.as_view(),name='thank_you'),
    path('contact/',ContactFormView.as_view(),name='contact'),
    path('create_teacher/',TeacherCreateView.as_view(), name='create_teacher'),
    path('teacher_list/',TeacherListView.as_view(), name='teacher_list'),
    path('teacher_detail/<int:pk>/',TeacherDetailView.as_view(), name='teacher_detail'),
    path('teacher_update/<int:pk>/',TeacherUpdateView.as_view(), name='teacher_update'),
    path('teacher_delete/<int:pk>/',TeacherDeleteView.as_view(),name='teacher_delete')
    ]

Django Class Based Views/school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/',include("classroom.urls"))
]

Django Class Based Views/school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

Django Class Based Views/school/classroom/forms.py
from django import forms

class ContractForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

Django Class Based Views/school/classroom/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from classroom.forms import ContractForm
from classroom.models import Teacher

# Create your views here.

class HomeView(TemplateView):
    template_name = 'classroom/home.html'

class ThankYouView(TemplateView):
    template_name = "classroom/thank_you.html"

class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:thank_you')

class ContactFormView(FormView):
    form_class = ContractForm
    template_name = "classroom/contact.html"

    success_url = reverse_lazy('classroom:thank_you')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)

class TeacherListView(ListView):
    model = Teacher
    #Default
    queryset = Teacher.objects.all()
    context_object_name = 'teacher_list'

class TeacherDetailView(DetailView):
    model = Teacher

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy("classroom:teacher_list")

class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('classroom:teacher_list')

Django Class Based Views/school/classroom/templates/classroom/contact.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form method="POST">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

Django Class Based Views/school/classroom/templates/classroom/home.html
<h1>Home page!</h1>
<ul>
    <li>
        <a href='{% url "classroom:thank_you" %}'>Thank you link</a>
    </li>
    <li>
        <a href='{% url 'classroom:contact' %}'>Contact Form link</a>
    </li>
    <li>
        <a href='{% url "classroom:create_teacher" %}'>Create New Teacher Form link</a>
    </li>
    <li>
        <a href='{% url "classroom:teacher_list" %}'>Teacher list View</a>
    </li>
</ul>

Django Class Based Views/school/classroom/templates/classroom/teacher_confirm_delete.html
<h2>Are u sure about this?</h2>
<h2>{{teacher}}</h2>
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

Django Class Based Views/school/classroom/templates/classroom/teacher_detail.html
<h1>Teacher Detail View</h1>
{{teacher}}

Django Class Based Views/school/classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>
<form action="" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Value">
</form>

Django Class Based Views/school/classroom/templates/classroom/teacher_list.html
<h1>Teacher List View</h1>
<ul>
{% for teacher in teacher_list %}
    <li>
        <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
        <ul>
            <li>
                <a href="/classroom/teacher_update/{{teacher.id}}">Update</a>
            </li>
            <li>
                <a href="/classroom/teacher_delete/{{teacher.id}}">Delete</a>
            </li>
        </ul>    
    </li>    
{% endfor %}
</ul>

Django Class Based Views/school/classroom/templates/classroom/thank_you.html
<h1>Thank you!</h1>